# Generated by Django 3.0.5 on 2020-05-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blog_entry',
            field=models.URLField(blank=True),
        ),
    ]
